### PR TITLE
Feature/json stat2 show presentation format pbi 133016

### PR DESCRIPTION
**Pull request by KentMossback**

### CODE REVIEW

**Review by JohannesFinsveen — CHANGES_REQUESTED** [review]
It seems the Jsonstat2Serializer.cs starts at 1 and  px-file_format_specification_2013.pdf start at 0 :-) 
Could we make an enum similar to PCAxis.Core/Enums/InformationLevelType.vb to avoid this? 
(I added a pxfile in the testfiles folder which uses prestext )

**Comment by KentMossback** [comment]
> It seems the Jsonstat2Serializer.cs starts at 1 and px-file_format_specification_2013.pdf start at 0 :-) Could we make an enum similar to PCAxis.Core/Enums/InformationLevelType.vb to avoid this? (I added a pxfile in the testfiles folder which uses prestext )

Yes, that seems lika a good idea. I was uncertain where to place a Enum like that.

**Review by likp — CHANGES_REQUESTED** [review]
@JohannesFinsveen already mention it that the index i the PX file format start from 0. The same goes for Paxiom.

In addtion 1 (value) is the default if not specified so GetPresentationForm should use that as default instead of null

**Review by MikaelNordberg — APPROVED** [review]
Looks good

**Review by likp — APPROVED** [review]
Looks good.

**Pull request merged**
