### PR TITLE
Bumped version of nuget packages

### PR DESCRIPTION
**Pull request by likp**
Bumped version of PCAxis.Core and PCAxis.Query and removed PCAxis.Comon and PCAxis.PX.Core

### CODE REVIEW

**Comment by likp** [comment]
@JohannesFinsveen the unit tests for SDMX fails, but they failed even before the bump. Can you give it a look?

**Comment by JohannesFinsveen** [comment]
@likp Works on my PC :-) Probably missing a file ...

**Comment by JohannesFinsveen** [comment]
@likp No such luck, its working for @oyessb as well ...  time for Actions to shine :-) ...

**Comment by JohannesFinsveen** [comment]
The good news: Actions reproduces the problem.
 
@likp,  its jsonstat failing not sdmx,  ? Or is this another problem?
In Norway it passes, but github gets  this: 
 Assert.AreEqual failed. Expected:<updated":"2006-07-05T12:21:00Z","value":>. Actual:<updated":"2006-07-05T14:21:00Z","value":>.
2 hours off, both with norwegian and finnish culture. Always more to learn about datetimes :-)

**Comment by likp** [comment]
It is the FullStringEqualTest that is failing for UnitTest.Sdmx It looks like it contains the byteorder marker U+FEFF in the catual output which cuases the assertion to fail

image

**Comment by JohannesFinsveen** [comment]
> All JsonStat test passes.
So there are two issues ...

**Comment by likp** [comment]
Should accept this change and create an issue for the test that are failing since the test where failing even before the changes?

**Comment by likp** [comment]
Ignored the failing unit tests

**Pull request merged**
